CREATE DATABASE musica;
CREATE DATABASE musica2;

USE musica;

CREATE TABLE Cantante(
	DNI INT NOT NULL,
	Nombre VARCHAR(30) NOT NULL,
	Apellido VARCHAR(30) NOT NULL,
	CONSTRAINT PK_DniMusico PRIMARY KEY (DNI)
)

use musica2;

CREATE TABLE Cantante(
	DNI INT NOT NULL,
	Nombre VARCHAR(30) NOT NULL,
	Apellido VARCHAR(30) NOT NULL,
	CONSTRAINT PK_DniMusico PRIMARY KEY (DNI)
)